baseURL = "https://example.com/"
languageCode = "en-us"
title = "Destrophix"
theme = "lekh"

[params]
Name = "Amit Bhagat"
About = "Otaku and Mechanical keyboard enthusiast"
Email = "amitbhagat963@gmail.com"
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/destrophix"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/destrophix"

[[params.profiles]]
name = "Book"
url = "https://app.thestorygraph.com/profile/destrophix"

[[params.profiles]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/bhagat-amit"

